global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: ordering
    metrics_path: /actuator/prometheus
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/ordering.yml
        refresh_interval: 5s
